# Generated by Django 2.0.4 on 2018-04-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180414_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='kids',
        ),
    ]
