# Generated by Django 2.0.4 on 2018-04-22 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_photo_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padre_del_niño', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madre_del_niño', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='parents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='padre_del_niño', to='webapp.Parents'),
            preserve_default=False,
        ),
    ]
