# Generated by Django 2.0.4 on 2018-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180422_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_location',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=1, max_length=254, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
