# Generated by Django 2.0.4 on 2018-04-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180428_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='photos/generic_baby.jpg', max_length=254, upload_to='photos/'),
        ),
    ]
