# Generated by Django 2.0.4 on 2018-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180428_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.IntegerField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
