# Generated by Django 2.0.4 on 2018-04-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180429_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
