# Generated by Django 2.0.4 on 2018-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180429_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
    ]
