# Generated by Django 2.0.4 on 2018-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180429_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
