# Generated by Django 2.0.4 on 2018-04-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180429_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parents',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='padre_del_niño', to='webapp.Parents'),
        ),
    ]
