# Generated by Django 2.0.4 on 2018-04-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20180429_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='padre_del_niño', to='webapp.Parents'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='kids',
            field=models.ManyToManyField(default=1, to='webapp.Kid'),
        ),
    ]
